# TODO Only do release builds on the `pull` branch?

jobs:
  include:
# - os: linux
#   language: nix
#   nix: 2.1.3
#   install:
#     - nix-env -iA cachix -f https://cachix.org/api/v1/install

#   script:
#     - cachix use urbit2
#     - ./sh/cachix
#     - make build-fast
#     - make release
#     - sh/ci-tests

  - os: osx
    language: generic
    sudo: required
    script:
      - ver="$(git rev-parse HEAD)"
      - if [ -n "${TRAVIS_COMMIT-}" ]; then ver="$TRAVIS_COMMIT"; fi
      - if [ -n "${TRAVIS_TAG-}" ]; then ver="$TRAVIS_TAG"; fi
      - stack clean
      - stack install king --local-bin-path ./release
      - mv release/king release/king-darwin-$ver
      - otool -L release/king-darwin-$ver

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

before_install:
  - git lfs pull
  - sh/travis-install-stack

install:
  - stack --no-terminal --install-ghc build king --only-dependencies

deploy:
  - skip_cleanup: true
    provider: gcs
    access_key_id: GOOGTADOPP55X5ZTH3IKAXQW
    secret_access_key:
      secure: rSPif0VHX3Q3QpWM9iUt/Z9sicCY8ABuwVFPeT3YUnAAmSXM46PIHKieoGs79kx9IelFyQsM8xS0XWyt4S/haR7VaTJY+zHJjf0AnA1sr5ZIV70t3K0SXzq4+E1ffOZRiC0VmHatPz10wjaIpHxpjcROqQV4M1dBCq2H/rpccIE=
    bucket: bootstrap.urbit.org
    local-dir: release/
    acl: public-read
    on:
      condition: "-d release/"
      repo: urbit/urbit
      all_branches: true
