language: nix
nix: 2.1.3

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

before_install:
  - git lfs pull
  - sh/travis-install-stack

install:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - stack --no-terminal --install-ghc build king --only-dependencies

# TODO Only do release builds on the `pull` branch?
script:
  - cachix use urbit2
  - ./sh/cachix || true
  - make build-fast
  - make release
  - sh/ci-tests

deploy:
  - skip_cleanup: true
    provider: gcs
    access_key_id: GOOGTADOPP55X5ZTH3IKAXQW
    secret_access_key:
      secure: rSPif0VHX3Q3QpWM9iUt/Z9sicCY8ABuwVFPeT3YUnAAmSXM46PIHKieoGs79kx9IelFyQsM8xS0XWyt4S/haR7VaTJY+zHJjf0AnA1sr5ZIV70t3K0SXzq4+E1ffOZRiC0VmHatPz10wjaIpHxpjcROqQV4M1dBCq2H/rpccIE=
    bucket: bootstrap.urbit.org
    local-dir: release/
    acl: public-read
    on:
      condition: "-d release/"
      repo: urbit/urbit
      all_branches: true
